# Section A : Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [88]:
# Question 1 - List of 5 Integers and Operations on the list

a = [24, 50, 33, 55, 39]
print("Initial list:", a)

a.append(2) #Appends 2 at the end of the list
print("\nafter append(2):", a)

a.extend([6, 7]) #Appends 6,7 at the end of the list
print("\nafter extend([6, 7]):", a)

a.insert(1, 26) # Inserts 26 at index 1
print("\nafter insert(1, 26):", a)

a.remove(50) #Removes first value of 50
print("\nafter remove(50):", a)

popped_val = a.pop(2) # Removes number at index 2
print(f"\nafter pop(2) [removed {popped_val}]:", a)

idx = a.index(39)
print("\nresult of index(39):", idx)

cnt = a.count(26) # returns count of exact value 26
print("\nresult of count(26):", cnt)

a.sort(reverse=True) # sorts in descending order
print("\nafter sort(reverse=True):", a)

a.reverse() # Reverses the entire list
print("\nafter reverse():", a)

a.clear() # Removes all elements in the list
print("\nafter clear():", a)

Initial list: [24, 50, 33, 55, 39]

after append(2): [24, 50, 33, 55, 39, 2]

after extend([6, 7]): [24, 50, 33, 55, 39, 2, 6, 7]

after insert(1, 26): [24, 26, 50, 33, 55, 39, 2, 6, 7]

after remove(50): [24, 26, 33, 55, 39, 2, 6, 7]

after pop(2) [removed 33]: [24, 26, 55, 39, 2, 6, 7]

result of index(39): 3

result of count(26): 1

after sort(reverse=True): [55, 39, 26, 24, 7, 6, 2]

after reverse(): [2, 6, 7, 24, 26, 39, 55]

after clear(): []

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [89]:
# Question 2 - Tuple operations

a_tuple = ("Dimpu","Narasimha","Sai")
a_tuple[1] = "Ram"

TypeError: 'tuple' object does not support item assignment

**Explanation :**

If we try to change the second name in tuple it returns a **TypeError**.

This happens because **Tuples are Immutable**. Once a tuple is created, its elements cannot be modified, added, removed or reassigned.

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [90]:
# Question 3 - Created a set with duplicate values

a_set = {65,23,26,26,91,76,33,91}
a_set

{23, 26, 33, 65, 76, 91}

**Explanation :**

The set i had created contains duplicates of 26 and 91.
But when i had printed the set it had removed duplicates and only unique values are kept.

- sets in python automatically eliminates duplicates

- every element in a set must be unique

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [91]:
# Question 4 - created a dictionary with keys : 'name', 'age', 'city'

a_dict = {"name":"Dimpu",
          "age":21,
          "city":"Vijayawada"}
print("Initial Dictionary :",a_dict)

# Update existing key "age"
a_dict["age"] = 22

#add new key "email"
a_dict["email"] = "dimpu.b2085@gmail.com"

print("\nFinal Dictionary :" ,a_dict)

Initial Dictionary : {'name': 'Dimpu', 'age': 21, 'city': 'Vijayawada'}

Final Dictionary : {'name': 'Dimpu', 'age': 22, 'city': 'Vijayawada', 'email': 'dimpu.b2085@gmail.com'}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [92]:
# Question 5 - Script to check if person is eligible to vote

age = int(input("Enter Age : "))
if (age<0):
  print("Age cannot be negative.")
elif(age>=18):
  print("Congrats! You are eligible to VOTE.")
else:
  print("Sorry! You are not eligible to VOTE.")

Enter Age : 21
Congrats! You are eligible to VOTE.

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [93]:
# Question 6 - Print the grade for the given marks

marks = int(input("Enter marks : "))

if (marks<0 or marks>100):
  print("Invalid Marks! Please enter a value between 0 and 100.")
elif(marks>=90):
  print("Grade : A")
elif(marks>=75):
  print("Grade : B")
elif(marks>=50):
    print("Grade : C")
else:
  print("Grade : Fail")

Enter marks : 64
Grade : C

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [94]:
# Question 7 - Check +ve, even , -ve, zero

a = int(input("Enter a number: "))

if a > 0:
    print(f"{a} is positive")
    if a % 2 == 0:
        print(f"{a} is even")
    else:
        print(f"{a} is odd")
elif a == 0:
    print("The number is zero")
else:
    print(f"{a} is negative")

Enter a number: 4
4 is positive
4 is even

#Section B : Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [95]:
# Question 8
import numpy as np

# 1. Scalar using np.array(5)
scalar = np.array(5)

# 2. 1D Array with values 1 to 5
arr_1D = np.arange(1,6)

#3. 2D Array (2x3) with values from 10 to 60 in steps of 10
arr_2D = np.arange(10,70,10).reshape(2,3)

# Displaying Results
print("Scalar : ", scalar, '\nShape : ', scalar.shape)
print("\n1D Array : \n", arr_1D)
print("\n2D array (2x3) : \n", arr_2D)

Scalar :  5
Shape :  ()

1D Array :
 [1 2 3 4 5]

2D array (2x3) :
 [[10 20 30]
 [40 50 60]]

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [96]:
# Question 9
import numpy as np

# generate a 4x4 numpy array of random integers between 0 and 100
arr = np.random.randint(0,101, size = (4,4))
print("4x4 Numpy array of random integers between 0 to 100 : \n",arr)

4x4 Numpy array of random integers between 0 to 100 :
 [[99 81 38 57]
 [89 56 48 76]
 [16  9 77 48]
 [ 8 21 84 67]]

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [97]:
# Question 10

import numpy as np
import pandas as pd

#Creating a 2D numpy Array of shape (3x3)
arr1 = np.arange(10,28,2).reshape(3,3)
print("2D numpy array of shape 3x3 : \n",arr1)

#Converting 2D array (3x3) in to a pandas DataFrame with column names : "A","B","C"
df = pd.DataFrame(arr1,columns = ['A','B','C'])
print("\nPandas Dataframe : \n",df)

2D numpy array of shape 3x3 :
 [[10 12 14]
 [16 18 20]
 [22 24 26]]

Pandas Dataframe :
     A   B   C
0  10  12  14
1  16  18  20
2  22  24  26

#Section C : Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [98]:
# Question 11

import numpy as np
import pandas as pd

# 1. Create a DataFrame with 10 rows containing missing values and duplicates
data = { "Name": ["Alice","Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hank", "Alice", "Ivy", ],

         "Age": [25, 30, 35, 40, 28, 32, 45, 29, 25, 31],

         "City": ["New York","London","Paris","Tokyo","Berlin","London","Paris","Tokyo","New York","Berlin",],

         "Salary": [70000,80000,np.nan,95000,62000,80000,110000,np.nan,70000,68000,],
         }

df = pd.DataFrame(data)
print("\n---------------Initial Dataframe---------------")
print(df)

---------------Initial Dataframe---------------
      Name  Age      City    Salary
0    Alice   25  New York   70000.0
1      Bob   30    London   80000.0
2  Charlie   35     Paris       NaN
3    David   40     Tokyo   95000.0
4      Eva   28    Berlin   62000.0
5    Frank   32    London   80000.0
6    Grace   45     Paris  110000.0
7     Hank   29     Tokyo       NaN
8    Alice   25  New York   70000.0
9      Ivy   31    Berlin   68000.0

In [99]:
# 2. USE .info()
print("\n---------------.info()---------------\n")
df.info()

---------------.info()---------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [100]:
# 3. USE .describe()
print("\n---------------.describe()---------------\n")
df.describe()

---------------.describe()---------------

             Age         Salary
count  10.000000       8.000000
mean   32.000000   79375.000000
std     6.411795   15990.510579
min    25.000000   62000.000000
25%    28.250000   69500.000000
50%    30.500000   75000.000000
75%    34.250000   83750.000000
max    45.000000  110000.000000

In [101]:
# 4. Select Name and City columns
df[["Name","City"]]

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo
4      Eva    Berlin
5    Frank    London
6    Grace     Paris
7     Hank     Tokyo
8    Alice  New York
9      Ivy    Berlin

In [102]:
# 5. Delete City Column
df = df.drop(columns="City", axis = 1)
df

      Name  Age    Salary
0    Alice   25   70000.0
1      Bob   30   80000.0
2  Charlie   35       NaN
3    David   40   95000.0
4      Eva   28   62000.0
5    Frank   32   80000.0
6    Grace   45  110000.0
7     Hank   29       NaN
8    Alice   25   70000.0
9      Ivy   31   68000.0

In [103]:
# 6. Fill missing values in 'Salary' column with mean
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

      Name  Age    Salary
0    Alice   25   70000.0
1      Bob   30   80000.0
2  Charlie   35   79375.0
3    David   40   95000.0
4      Eva   28   62000.0
5    Frank   32   80000.0
6    Grace   45  110000.0
7     Hank   29   79375.0
8    Alice   25   70000.0
9      Ivy   31   68000.0

In [104]:
# 7. Remove Duplicates
df = df.drop_duplicates()
df

      Name  Age    Salary
0    Alice   25   70000.0
1      Bob   30   80000.0
2  Charlie   35   79375.0
3    David   40   95000.0
4      Eva   28   62000.0
5    Frank   32   80000.0
6    Grace   45  110000.0
7     Hank   29   79375.0
9      Ivy   31   68000.0