In [43]:
import pandas as pd
import numpy as np

In [44]:
# 1.Load the patient dataset

# Raw URLs for direct CSV reading
patient_url = "https://raw.githubusercontent.com/Bumb1eBee20/ExcelR---Data-Science-Assignments-Submissions/22e13b7df95bb5fd6daedc8be3acb7cd7501135a/4.%20Basic%20Stats%20-%202/data/Patient_Data.csv"
billing_url = "https://raw.githubusercontent.com/Bumb1eBee20/ExcelR---Data-Science-Assignments-Submissions/22e13b7df95bb5fd6daedc8be3acb7cd7501135a/4.%20Basic%20Stats%20-%202/data/Billing_Data.csv"

df_patient = pd.read_csv(patient_url)
df_billing = pd.read_csv(billing_url)

In [45]:
print("=" * 80)
print("PATIENT DATA")
print("=" * 80)

display(df_patient)

================================================================================
PATIENT DATA
================================================================================

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

**Load Patient Dataset and Show Summary with info()**

In [46]:
print("=" * 80)
print("PATIENT DATA SUMMARY")
print("=" * 80)

# Dataset information
df_patient.info()

# Shape
print("\nShape:", df_patient.shape)

# Number of rows
print("Number of Rows:", df_patient.shape[0])

# Number of columns
print("Number of Columns:", df_patient.shape[1])

# Null values
print("\nNull Values:")
print(df_patient.isnull().sum())

# Duplicate rows
print("\nDuplicate Rows:")
print(df_patient.duplicated().sum())

================================================================================
PATIENT DATA SUMMARY
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

Shape: (6, 7)
Number of Rows: 6
Number of Columns: 7

Null Values:
PatientID         0
Name              0
Department        0
Doctor            0
BillAmount        2
ReceptionistID    0
CheckInTime       0
dtype: int64

Duplicate Rows:
1

**Select Relevant Billing Columns**

In [47]:
#Selecting Relevant Billing Columns
billing_patient = df_patient[
    ["PatientID", "Department", "Doctor", "BillAmount"]
]

print("=" * 80)
print("BILLING-RELATED PATIENT DATA")
print("=" * 80)

display(billing_patient)

================================================================================
BILLING-RELATED PATIENT DATA
================================================================================

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

**Drop Administrative Columns**

In [48]:
# Dropping Administrative cols
df_patient = df_patient.drop(
    columns=["ReceptionistID", "CheckInTime"]
)

print("=" * 80)
print("PATIENT DATA AFTER DROPPING ADMINISTRATIVE COLUMNS")
print("=" * 80)

display(df_patient)

================================================================================
PATIENT DATA AFTER DROPPING ADMINISTRATIVE COLUMNS
================================================================================

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

**Remove Duplicate Patient Records based on PatientID**

In [49]:
print("Duplicate PatientIDs before removal:",
      df_patient["PatientID"].duplicated().sum())

df_patient = df_patient.drop_duplicates(
    subset="PatientID",
    keep="first"
).reset_index(drop=True)

print("Duplicate PatientIDs after removal:",
      df_patient["PatientID"].duplicated().sum())

display(df_patient)

Duplicate PatientIDs before removal: 1
Duplicate PatientIDs after removal: 0

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

**Fill Missing BillAmount with Mean**

In [50]:
#Calculate Mean
mean_bill = df_patient["BillAmount"].mean()

print("Mean Bill Amount:", mean_bill)

df_patient["BillAmount"] = df_patient["BillAmount"].fillna(
    mean_bill
)

print("=" * 80)
print("PATIENT DATA AFTER FILLING MISSING BILL AMOUNTS")
print("=" * 80)

display(df_patient)

Mean Bill Amount: 6233.333333333333
================================================================================
PATIENT DATA AFTER FILLING MISSING BILL AMOUNTS
================================================================================

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

**Total Bill Amount Per Department**

In [51]:

department_bill = (
    df_patient
    .groupby("Department")["BillAmount"]
    .sum()
    .reset_index()
)

department_bill.columns = [
    "Department",
    "Total_BillAmount"
]

print("=" * 80)
print("TOTAL BILL AMOUNT PER DEPARTMENT")
print("=" * 80)

display(department_bill)

================================================================================
TOTAL BILL AMOUNT PER DEPARTMENT
================================================================================

    Department  Total_BillAmount
0   Cardiology      11200.000000
1  Dermatology       6233.333333
2    Neurology       6233.333333
3  Orthopedics       7500.000000

In [52]:
print("Missing BillAmount values:",
      df_patient["BillAmount"].isnull().sum())

Missing BillAmount values: 0

**Merge Billing Dataset with Patient Dataset**

In [53]:
print("=" * 80)
print("BILLING DATA")
print("=" * 80)

display(df_billing)

# .info()
print("\nBilling Data Information:")
df_billing.info()

#Checking Null values
print("\nNull Values:")
print(df_billing.isnull().sum())

#Checking Duplicate values
print("\nDuplicate Rows:")
print(df_billing.duplicated().sum())

================================================================================
BILLING DATA
================================================================================

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

Billing Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

Null Values:
PatientID           0
InsuranceCovered    0
FinalAmount         0
dtype: int64

Duplicate Rows:
0

In [54]:
df_merged = pd.merge(
    df_patient,
    df_billing,
    on="PatientID",
    how="left"
)

print("=" * 80)
print("MERGED PATIENT + BILLING DATA")
print("=" * 80)

display(df_merged)

================================================================================
MERGED PATIENT + BILLING DATA
================================================================================

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [55]:
print("=" * 80)
print("MERGED DATASET SUMMARY")
print("=" * 80)

#shape
print("Shape:", df_merged.shape)

# checking null values
print("\nNull Values:")
print(df_merged.isnull().sum())

# Checking Data types
print("\nData Types:")
print(df_merged.dtypes)

================================================================================
MERGED DATASET SUMMARY
================================================================================
Shape: (5, 7)

Null Values:
PatientID           0
Name                0
Department          0
Doctor              0
BillAmount          0
InsuranceCovered    0
FinalAmount         0
dtype: int64

Data Types:
PatientID             int64
Name                 object
Department           object
Doctor               object
BillAmount          float64
InsuranceCovered      int64
FinalAmount           int64
dtype: object

**Concatenate New Patients Row-wise**

In [56]:
new_patients = pd.DataFrame({
    "PatientID": [106, 107],
    "Name": ["Frank", "Grace"],
    "Department": ["Cardiology", "Neurology"],
    "Doctor": ["Dr. Smith", "Dr. John"],
    "BillAmount": [6800.0, 5400.0],
    "ReceptionistID": [1, 2],
    "CheckInTime": [
        "2023-01-16 09:30",
        "2023-01-17 10:15"
    ]
})

print("=" * 80)
print("NEW PATIENTS")
print("=" * 80)

display(new_patients)

================================================================================
NEW PATIENTS
================================================================================

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,106,Frank,Cardiology,Dr. Smith,6800.0,1,2023-01-16 09:30
1,107,Grace,Neurology,Dr. John,5400.0,2,2023-01-17 10:15

In [57]:
# Select only columns matching the cleaned patient dataset
new_patients_clean = new_patients[
    ["PatientID", "Name", "Department", "Doctor", "BillAmount"]
]
new_patients_clean

   PatientID   Name  Department     Doctor  BillAmount
0        106  Frank  Cardiology  Dr. Smith      6800.0
1        107  Grace   Neurology   Dr. John      5400.0

In [58]:
df_patient_updated = pd.concat(
    [
        df_patient,
        new_patients_clean
    ],
    axis=0,
    ignore_index=True
)

print("=" * 80)
print("PATIENT DATA AFTER ROW-WISE CONCATENATION")
print("=" * 80)

display(df_patient_updated)

================================================================================
PATIENT DATA AFTER ROW-WISE CONCATENATION
================================================================================

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333
5        106    Frank   Cardiology  Dr. Smith  6800.000000
6        107    Grace    Neurology   Dr. John  5400.000000

In [59]:
print("Original patient rows:", len(df_patient))
print("New patient rows:", len(new_patients_clean))
print("Updated patient rows:", len(df_patient_updated))

Original patient rows: 5
New patient rows: 2
Updated patient rows: 7

**Concatenate Billing Columns Column - wise**

In [60]:
billing_columns = df_billing[
    ["InsuranceCovered", "FinalAmount"]
]

print("=" * 80)
print("BILLING COLUMNS")
print("=" * 80)

display(billing_columns)

================================================================================
BILLING COLUMNS
================================================================================

   InsuranceCovered  FinalAmount
0              2000         3000
1              1500         3500
2              2500         5000
3              3000         3200
4              1000         4000

In [61]:
df_final = pd.concat(
    [
        df_patient,
        billing_columns
    ],
    axis=1
)

print("=" * 80)
print("FINAL DATASET AFTER COLUMN-WISE CONCATENATION")
print("=" * 80)

display(df_final)

================================================================================
FINAL DATASET AFTER COLUMN-WISE CONCATENATION
================================================================================

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

**Final Cleaned Dataset**

In [62]:
print("=" * 80)
print("FINAL CLEANED DATASET")
print("=" * 80)

display(df_final)

print("\nFinal Shape:", df_final.shape)

print("\nFinal Data Types:")
print(df_final.dtypes)

print("\nFinal Null Values:")
print(df_final.isnull().sum())

================================================================================
FINAL CLEANED DATASET
================================================================================

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

Final Shape: (5, 7)

Final Data Types:
PatientID             int64
Name                 object
Department           object
Doctor               object
BillAmount          float64
InsuranceCovered      int64
FinalAmount           int64
dtype: object

Final Null Values:
PatientID           0
Name                0
Department          0
Doctor              0
BillAmount          0
InsuranceCovered    0
FinalAmount         0
dtype: int64